### PR TITLE
Added a method to get the TagAPI version.

### PR DESCRIPTION
**Pull request by aarontwf**

### CODE REVIEW

**Comment by mbax** [comment]
...

Why?

**Comment by ammaraskar** [comment]
:laughing:

**Comment by aarontwf** [comment]
Auto updater.

**Comment by mbax** [comment]
Are you going around asking for static version methods in all plugins you use?

**Comment by aarontwf** [comment]
Nope, just realized I get the TagAPI instance anyway so don't need it.

**Pull request closed without merging**
